### ISSUE TITLE
jpg resizes to container width but sticks to original height

### ISSUE THREAD

**Issue by christophberger** [stereobooster/hugo-ideal-image#1]
Hi @stereobooster,

Thanks a lot for this awesome image resize tool. 

One minor problem I encountered: My images got resized to the container's width (so they fit nicely within the text column), but the height was left at the original height, leading to grossly distorted images with dimensions like, e.g., 581x3349. 

I "fixed" this be removing the [width and height attributes](https://github.com/stereobooster/hugo-ideal-image/blob/5972694c193acbff2af8e910955ffb75f4d95dca/layouts/partials/picture.html#L77C1-L79C31) from the img tag in `picture.html`, that is, changing  the tag from:

```gotpl
      <img
        width="{{ .Width }}"
        height="{{ .Height }}"
```

to just `<img`.  

This quick-fixes the distortion, but I think this introduces CLS.

How can I get/calculate the correct, scaled height?

**Comment by christophberger** [comment]
Fix: In CSS:

```css
img {
    max-width: 100%;
    height: auto;
}
```

Now image resize works as intended, with zero CLS

**Comment by stereobooster** [comment]
https://github.com/stereobooster/hugo-ideal-image#image-css

**Comment by christophberger** [comment]
Yeaaaaaah "RTFM" ☺️
